server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: profile-service
              uri: http://profile-service:8081
              predicates:
                - Path=/api/v1/profiles,/api/v1/profiles/**

            - id: feedback-service
              uri: http://feedback-service:8082
              predicates:
                - Path=/api/v1/feedback,/api/v1/feedback/**

          global-cors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"